### ISSUE TITLE
Two optionPopup.popup on single view don't work

### ISSUE THREAD

**Issue by Odhrean** [davidsowerby/krail#423]
Two Buttons with different optionPopup.popup OptionContext's don't work.

i.e.:
```Java
public class MyNews extends Grid3x3ViewBase implements OptionContext{
```
```Java
	private TutorialUI ui;

	@Inject
	public MyNews(Option option,OptionPopup _optionPopup,TutorialUI _ui) {
		this.option = option;
		optionPopup = _optionPopup;
		ui = _ui;
	}
```
```Java
		popupButton = new Button("news options");
		popupButton.addClickListener(event -> optionPopup.popup(this,LabelKey.News_Options));
		setBottomCentre(popupButton);

		uiButton = new Button("ui options");
		uiButton.addClickListener(event -> optionPopup.popup(ui,LabelKey.UI_Options));
		setBottomLeft(uiButton);
```

I don't know if it is supposed to work... could be nice if it works.
Then it is possible to build a view with options for different contexts.

**Comment by davidsowerby** [comment]
mm - seems like this should work, but I haven't tried it yet - was the first popup closed before opening the second one?

**Comment by Odhrean** [comment]
I tried different things:
* Opening UI Option -> closing -> opening News option =>The content of UI Option is shown in News option too
* Opening UI Option -> opening News Option =>  Both Popups show the content of UI Option
* Opening News Option -> closing -> opening UI Option => App Crashes
